import Head from "next/head";
import Image from "next/image";
import React, { useState, useRef } from "react";
import ConfettiExplosion from "react-confetti-explosion";

const BeMyValentines = () => {
  const [yes, setYes] = useState(false);
  const [numbersOfNoClicked, set] = useState(0);
  const [noValueIdx, setIdx] = useState(0);

  const answerRef = useRef<HTMLDivElement>(null);

  const noValues = [
    "No",
    "Are you sure?",
    "Really?",
    "🌚 Okay, I'm begging",
    "Please Pookie",
    "PLEASE!!!",
    "I'll be very sad",
    "I'll be very very sad",
    "Okay fine, I'll stop asking : (",
    "Just kidding, PLEASE SAY YES 😭",
    "You're breaking my heart ; (",
  ];
  const noValue = noValues[noValueIdx];

  const handleIncrement = () => {
    set((prev) => prev + 1);

    if (noValueIdx >= noValues.length - 1) {
      setIdx(0);
      return;
    }
    setIdx((prev) => prev + 1);
  };

  const onYesClick = () => {
    setYes(true);
    set(0);
    if (answerRef.current) answerRef.current.style.display = "none";
  };

  const onNoClick = () => {
    alert(
      "I'm sorry, No is not an option! -- I'm gonna go ahead and select Yes for you 🌚💕♾️"
    );
    setYes(false);
  };

  return (
    <>
      <Head>
        <title>Valentine&apos;s Day Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-[#f9f9f9] text-gray-900 flex flex-col justify-center items-center px-4">
        <Image
          src={`/gif/${
            yes ? "bear-kiss-bear-kisses" : "cute-love-bear-roses"
          }.gif`}
          alt="22"
          width={200}
          height={200}
        />
        <p className="font-semibold text-2xl my-5">
          {yes
            ? "Thanks Pookie !!! 🌚🌚🌚🌚🌚"
            : "Will you be my Valentine? 💕♾️"}
        </p>

        <div
          ref={answerRef}
          className="flex flex-col md:flex-row flex-wrap items-center justify-center gap-2 md:gap-4 text-white w-full"
        >
          <button
            onClick={onYesClick}
            className="py-2.5 px-5 bg-green-500 hover:bg-green-700 font-bold min-w-[100px] rounded relative [&>div]:-top-5 [&>div]:me-auto [&>div]:m-auto break-all leading-none"
            style={{ fontSize: `${20 * (numbersOfNoClicked + 1) + 6}px` }}
          >
            {yes && (
              <ConfettiExplosion
                {...{
                  force: 0.8,
                  duration: 3000,
                  particleCount: 300,
                  width: 1600,
                  colors: [
                    "#041E43",
                    "#1471BF",
                    "#5BB4DC",
                    "#FC027B",
                    "#66D805",
                  ],
                }}
              />
            )}
            Yes
          </button>
          <button
            onClick={handleIncrement}
            className="py-2.5 px-5 bg-red-500 hover:bg-red-700 font-bold min-w-[100px] rounded"
          >
            {noValue}
          </button>
        </div>
      </div>
    </>
  );
};

export default BeMyValentines;
